// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: novedadesRequestBody.proto

package com.romanaaav.payloadcompressionexample.proto;

public final class NovedadesRequestBodyProto {
  private NovedadesRequestBodyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Novedades_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Novedades_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Novedades_DatosInspeccion_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Novedades_DatosInspeccion_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032novedadesRequestBody.proto\022\010tutorial\"\333" +
      "\t\n\tNovedades\022\021\n\004name\030\001 \001(\tH\000\210\001\001\022\017\n\002id\030\002 " +
      "\001(\005H\001\210\001\001\022\022\n\005email\030\003 \001(\tH\002\210\001\001\032\373\010\n\017DatosIn" +
      "speccion\022\017\n\002id\030\001 \001(\tH\000\210\001\001\022\020\n\003ver\030\002 \001(\tH\001" +
      "\210\001\001\022\030\n\013fecha_carga\030\003 \001(\tH\002\210\001\001\022\027\n\nhora_ca" +
      "rga\030\004 \001(\tH\003\210\001\001\022\027\n\nfecha_insp\030\005 \001(\tH\004\210\001\001\022" +
      "\026\n\thora_insp\030\006 \001(\tH\005\210\001\001\022\027\n\ncant_fotos\030\007 " +
      "\001(\005H\006\210\001\001\022\030\n\013aseguradora\030\010 \001(\005H\007\210\001\001\022\033\n\016nr" +
      "o_formulario\030\t \001(\tH\010\210\001\001\022\036\n\021nro_insp_tecn" +
      "ored\030\n \001(\tH\t\210\001\001\022!\n\024nro_insp_aseguradora\030" +
      "\013 \001(\tH\n\210\001\001\022\026\n\tinspector\030\014 \001(\tH\013\210\001\001\022\027\n\nfo" +
      "rmulario\030\r \001(\tH\014\210\001\001\022\031\n\014auditada_por\030\016 \001(" +
      "\tH\r\210\001\001\022\037\n\022id_usuario_barbara\030\017 \001(\005H\016\210\001\001\022" +
      "\033\n\016tipo_inspector\030\020 \001(\tH\017\210\001\001\022\026\n\tcobertur" +
      "a\030\021 \001(\tH\020\210\001\001\022\017\n\002cp\030\022 \001(\005H\021\210\001\001\022%\n\030motivo_" +
      "rechazo_cobertura\030\023 \001(\tH\022\210\001\001\022 \n\023resultad" +
      "o_auditoria\030\024 \001(\tH\023\210\001\001\022\024\n\007latitud\030\025 \001(\tH" +
      "\024\210\001\001\022\025\n\010longitud\030\026 \001(\tH\025\210\001\001\022\024\n\007id_repo\030\027" +
      " \001(\005H\026\210\001\001\022\020\n\003url\030\030 \001(\tH\027\210\001\001\022\030\n\013error_fot" +
      "os\030\031 \001(\tH\030\210\001\001\022\035\n\020observaciones_ia\030\032 \001(\tH" +
      "\031\210\001\001\022\026\n\talerta_ia\030\033 \001(\005H\032\210\001\001B\005\n\003_idB\006\n\004_" +
      "verB\016\n\014_fecha_cargaB\r\n\013_hora_cargaB\r\n\013_f" +
      "echa_inspB\014\n\n_hora_inspB\r\n\013_cant_fotosB\016" +
      "\n\014_aseguradoraB\021\n\017_nro_formularioB\024\n\022_nr" +
      "o_insp_tecnoredB\027\n\025_nro_insp_aseguradora" +
      "B\014\n\n_inspectorB\r\n\013_formularioB\017\n\r_audita" +
      "da_porB\025\n\023_id_usuario_barbaraB\021\n\017_tipo_i" +
      "nspectorB\014\n\n_coberturaB\005\n\003_cpB\033\n\031_motivo" +
      "_rechazo_coberturaB\026\n\024_resultado_auditor" +
      "iaB\n\n\010_latitudB\013\n\t_longitudB\n\n\010_id_repoB" +
      "\006\n\004_urlB\016\n\014_error_fotosB\023\n\021_observacione" +
      "s_iaB\014\n\n_alerta_iaB\007\n\005_nameB\005\n\003_idB\010\n\006_e" +
      "mailBL\n-com.romanaaav.payloadcompression" +
      "example.protoB\031NovedadesRequestBodyProto" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_Novedades_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_Novedades_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Novedades_descriptor,
        new java.lang.String[] { "Name", "Id", "Email", "Name", "Id", "Email", });
    internal_static_tutorial_Novedades_DatosInspeccion_descriptor =
      internal_static_tutorial_Novedades_descriptor.getNestedTypes().get(0);
    internal_static_tutorial_Novedades_DatosInspeccion_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Novedades_DatosInspeccion_descriptor,
        new java.lang.String[] { "Id", "Ver", "FechaCarga", "HoraCarga", "FechaInsp", "HoraInsp", "CantFotos", "Aseguradora", "NroFormulario", "NroInspTecnored", "NroInspAseguradora", "Inspector", "Formulario", "AuditadaPor", "IdUsuarioBarbara", "TipoInspector", "Cobertura", "Cp", "MotivoRechazoCobertura", "ResultadoAuditoria", "Latitud", "Longitud", "IdRepo", "Url", "ErrorFotos", "ObservacionesIa", "AlertaIa", "Id", "Ver", "FechaCarga", "HoraCarga", "FechaInsp", "HoraInsp", "CantFotos", "Aseguradora", "NroFormulario", "NroInspTecnored", "NroInspAseguradora", "Inspector", "Formulario", "AuditadaPor", "IdUsuarioBarbara", "TipoInspector", "Cobertura", "Cp", "MotivoRechazoCobertura", "ResultadoAuditoria", "Latitud", "Longitud", "IdRepo", "Url", "ErrorFotos", "ObservacionesIa", "AlertaIa", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
