// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: novedadesRequestBody.proto

package com.romanaaav.payloadcompressionexample.proto;

public interface NovedadesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.Novedades)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string hash = 1;</code>
   * @return Whether the hash field is set.
   */
  boolean hasHash();
  /**
   * <code>optional string hash = 1;</code>
   * @return The hash.
   */
  java.lang.String getHash();
  /**
   * <code>optional string hash = 1;</code>
   * @return The bytes for hash.
   */
  com.google.protobuf.ByteString
      getHashBytes();

  /**
   * <code>optional .tutorial.Novedades.DatosInspeccion datos_inspeccion = 2;</code>
   * @return Whether the datosInspeccion field is set.
   */
  boolean hasDatosInspeccion();
  /**
   * <code>optional .tutorial.Novedades.DatosInspeccion datos_inspeccion = 2;</code>
   * @return The datosInspeccion.
   */
  com.romanaaav.payloadcompressionexample.proto.Novedades.DatosInspeccion getDatosInspeccion();
  /**
   * <code>optional .tutorial.Novedades.DatosInspeccion datos_inspeccion = 2;</code>
   */
  com.romanaaav.payloadcompressionexample.proto.Novedades.DatosInspeccionOrBuilder getDatosInspeccionOrBuilder();

  /**
   * <code>repeated .tutorial.Novedades.FotoNovedad fotos = 3;</code>
   */
  java.util.List<com.romanaaav.payloadcompressionexample.proto.Novedades.FotoNovedad> 
      getFotosList();
  /**
   * <code>repeated .tutorial.Novedades.FotoNovedad fotos = 3;</code>
   */
  com.romanaaav.payloadcompressionexample.proto.Novedades.FotoNovedad getFotos(int index);
  /**
   * <code>repeated .tutorial.Novedades.FotoNovedad fotos = 3;</code>
   */
  int getFotosCount();
  /**
   * <code>repeated .tutorial.Novedades.FotoNovedad fotos = 3;</code>
   */
  java.util.List<? extends com.romanaaav.payloadcompressionexample.proto.Novedades.FotoNovedadOrBuilder> 
      getFotosOrBuilderList();
  /**
   * <code>repeated .tutorial.Novedades.FotoNovedad fotos = 3;</code>
   */
  com.romanaaav.payloadcompressionexample.proto.Novedades.FotoNovedadOrBuilder getFotosOrBuilder(
      int index);
}
