// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: novedadesRequestBody.proto

package com.romanaaav.payloadcompressionexample.proto;

public final class NovedadesRequestBodyProto {
  private NovedadesRequestBodyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Novedades_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Novedades_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Novedades_DatosInspeccion_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Novedades_DatosInspeccion_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Novedades_FotoNovedad_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Novedades_FotoNovedad_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032novedadesRequestBody.proto\022\010tutorial\"\201" +
      "\013\n\tNovedades\022\021\n\004hash\030\001 \001(\tH\000\210\001\001\022B\n\020datos" +
      "_inspeccion\030\002 \001(\0132#.tutorial.Novedades.D" +
      "atosInspeccionH\001\210\001\001\022.\n\005fotos\030\003 \003(\0132\037.tut" +
      "orial.Novedades.FotoNovedad\032\373\010\n\017DatosIns" +
      "peccion\022\017\n\002id\030\001 \001(\tH\000\210\001\001\022\020\n\003ver\030\002 \001(\tH\001\210" +
      "\001\001\022\030\n\013fecha_carga\030\003 \001(\tH\002\210\001\001\022\027\n\nhora_car" +
      "ga\030\004 \001(\tH\003\210\001\001\022\027\n\nfecha_insp\030\005 \001(\tH\004\210\001\001\022\026" +
      "\n\thora_insp\030\006 \001(\tH\005\210\001\001\022\027\n\ncant_fotos\030\007 \001" +
      "(\005H\006\210\001\001\022\030\n\013aseguradora\030\010 \001(\005H\007\210\001\001\022\033\n\016nro" +
      "_formulario\030\t \001(\tH\010\210\001\001\022\036\n\021nro_insp_tecno" +
      "red\030\n \001(\tH\t\210\001\001\022!\n\024nro_insp_aseguradora\030\013" +
      " \001(\tH\n\210\001\001\022\026\n\tinspector\030\014 \001(\tH\013\210\001\001\022\027\n\nfor" +
      "mulario\030\r \001(\tH\014\210\001\001\022\031\n\014auditada_por\030\016 \001(\t" +
      "H\r\210\001\001\022\037\n\022id_usuario_barbara\030\017 \001(\005H\016\210\001\001\022\033" +
      "\n\016tipo_inspector\030\020 \001(\tH\017\210\001\001\022\026\n\tcobertura" +
      "\030\021 \001(\tH\020\210\001\001\022\017\n\002cp\030\022 \001(\005H\021\210\001\001\022%\n\030motivo_r" +
      "echazo_cobertura\030\023 \001(\tH\022\210\001\001\022 \n\023resultado" +
      "_auditoria\030\024 \001(\tH\023\210\001\001\022\024\n\007latitud\030\025 \001(\tH\024" +
      "\210\001\001\022\025\n\010longitud\030\026 \001(\tH\025\210\001\001\022\024\n\007id_repo\030\027 " +
      "\001(\005H\026\210\001\001\022\020\n\003url\030\030 \001(\tH\027\210\001\001\022\030\n\013error_foto" +
      "s\030\031 \001(\tH\030\210\001\001\022\035\n\020observaciones_ia\030\032 \001(\tH\031" +
      "\210\001\001\022\026\n\talerta_ia\030\033 \001(\005H\032\210\001\001B\005\n\003_idB\006\n\004_v" +
      "erB\016\n\014_fecha_cargaB\r\n\013_hora_cargaB\r\n\013_fe" +
      "cha_inspB\014\n\n_hora_inspB\r\n\013_cant_fotosB\016\n" +
      "\014_aseguradoraB\021\n\017_nro_formularioB\024\n\022_nro" +
      "_insp_tecnoredB\027\n\025_nro_insp_aseguradoraB" +
      "\014\n\n_inspectorB\r\n\013_formularioB\017\n\r_auditad" +
      "a_porB\025\n\023_id_usuario_barbaraB\021\n\017_tipo_in" +
      "spectorB\014\n\n_coberturaB\005\n\003_cpB\033\n\031_motivo_" +
      "rechazo_coberturaB\026\n\024_resultado_auditori" +
      "aB\n\n\010_latitudB\013\n\t_longitudB\n\n\010_id_repoB\006" +
      "\n\004_urlB\016\n\014_error_fotosB\023\n\021_observaciones" +
      "_iaB\014\n\n_alerta_ia\032Q\n\013FotoNovedad\022\025\n\010etiq" +
      "ueta\030\001 \001(\tH\000\210\001\001\022\023\n\006base64\030\002 \001(\tH\001\210\001\001B\013\n\t" +
      "_etiquetaB\t\n\007_base64B\007\n\005_hashB\023\n\021_datos_" +
      "inspeccionBL\n-com.romanaaav.payloadcompr" +
      "essionexample.protoB\031NovedadesRequestBod" +
      "yProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_Novedades_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_Novedades_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Novedades_descriptor,
        new java.lang.String[] { "Hash", "DatosInspeccion", "Fotos", "Hash", "DatosInspeccion", });
    internal_static_tutorial_Novedades_DatosInspeccion_descriptor =
      internal_static_tutorial_Novedades_descriptor.getNestedTypes().get(0);
    internal_static_tutorial_Novedades_DatosInspeccion_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Novedades_DatosInspeccion_descriptor,
        new java.lang.String[] { "Id", "Ver", "FechaCarga", "HoraCarga", "FechaInsp", "HoraInsp", "CantFotos", "Aseguradora", "NroFormulario", "NroInspTecnored", "NroInspAseguradora", "Inspector", "Formulario", "AuditadaPor", "IdUsuarioBarbara", "TipoInspector", "Cobertura", "Cp", "MotivoRechazoCobertura", "ResultadoAuditoria", "Latitud", "Longitud", "IdRepo", "Url", "ErrorFotos", "ObservacionesIa", "AlertaIa", "Id", "Ver", "FechaCarga", "HoraCarga", "FechaInsp", "HoraInsp", "CantFotos", "Aseguradora", "NroFormulario", "NroInspTecnored", "NroInspAseguradora", "Inspector", "Formulario", "AuditadaPor", "IdUsuarioBarbara", "TipoInspector", "Cobertura", "Cp", "MotivoRechazoCobertura", "ResultadoAuditoria", "Latitud", "Longitud", "IdRepo", "Url", "ErrorFotos", "ObservacionesIa", "AlertaIa", });
    internal_static_tutorial_Novedades_FotoNovedad_descriptor =
      internal_static_tutorial_Novedades_descriptor.getNestedTypes().get(1);
    internal_static_tutorial_Novedades_FotoNovedad_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Novedades_FotoNovedad_descriptor,
        new java.lang.String[] { "Etiqueta", "Base64", "Etiqueta", "Base64", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
